baseURL = "https://kamal2230.github.io/mlnotes/"
languageCode = "en-us"
title = "Kamal Khumar"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
