baseURL = "https://teamtact.github.io/hugobase/"
languageCode = "en-us"
title = "John Doe"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
